name: test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install
      - uses: actions/checkout@v2
        run:  |
          pip install poetry
          make install
      - name: test & publish
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
